# Generated by Django 5.0 on 2023-12-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogFull',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.basemodel')),
                ('title', models.CharField(help_text='Write title', max_length=255, verbose_name='title')),
                ('author', models.CharField(help_text='Write author', max_length=30, verbose_name='author')),
                ('image', models.ImageField(upload_to='blog_image/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Blog full',
                'verbose_name_plural': 'Blogs full',
            },
            bases=('blog.basemodel',),
        ),
    ]
